name: CI
on: [push, pull_request]
jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        bundler-cache: true

    - name: Run rubocop
      run: |
        bundle exec rubocop
